### ISSUE TITLE
Is it a thing ?

### ISSUE THREAD

**Issue by ncuillery** [joshuat/ant-design-sass#1]
Hi @joshua-turner 

Thanks for the repo. Stop me if I'm wrong but this repo simply contains a basic React app using the SASS portage of Antd stored in `public/`, it provides nothing about "how to generate that SASS portage".

So I have some questions:

- Which tools did you use ?
- Was it easy ?

**Comment by joshuat** [comment]
This was a little while ago - but I think I used [less2sass](https://github.com/ekryski/less2sass) to start, and did the rest by hand. There are a few issues with the less2sass library, specifically when dealing with colors.

The hardest part was porting the javascript functions that worked with less to postcss and get them working with webpack.

I would call it monotonous more than anything. Plenty of trial and error.
